CREATE TABLE networking_methods (
	Method Name VARCHAR(3),
	Long Name VARCHAR(27),
	Description TEXT
);

INSERT INTO networking_methods
VALUES
	('NAT','Network Address Translation','A method for translating private IP addresses to public IP addresses and vice versa.'),
	('DHCP','Dynamic Host Configuration Protocol','A network management protocol used to dynamically assign IP addresses to devices on a network.'),
	('DNS','Domain Name System','A hierarchical system for translating human-readable domain names to IP addresses.'),
	('NAT64','Network Address Translation 64','A technique that enables IPv6-enabled devices to communicate with IPv4 devices.'),
	('PAT','Port Address Translation','A type of NAT that maps multiple private IP addresses to a single public IP address using different port numbers.'),
	('VPN','Virtual Private Network','A method of securely connecting to a private network over a public network, like the internet.'),
	('QoS','Quality of Service','Techniques for managing network traffic to ensure the performance of critical applications.'),
	('VLAN','Virtual Local Area Network','A network configuration that allows you to segment a physical network into multiple logical networks.'),
	('MPLS','Multiprotocol Label Switching','A method for routing data based on labels rather than IP addresses, improving speed and efficiency.'),
	('Tunneling','Network Tunneling','A method for encapsulating one network protocol within another to securely transport data.'),
	('IDS','Intrusion Detection System','A system for monitoring network traffic for suspicious activity and potential security breaches.'),
	('IPS','Intrusion Prevention System','A network security technology that monitors and prevents malicious activities and policy violations.'),
	('ARP','Address Resolution Protocol','A protocol for mapping an IP address to a physical MAC address on a local network.'),
	('SNMP','Simple Network Management Protocol','A protocol for managing and monitoring network devices like routers and switches.'),
	('DHCPv6','Dynamic Host Configuration Protocol for IPv6','A version of DHCP used to assign IPv6 addresses dynamically.'),
	('STP','Spanning Tree Protocol','A protocol used to prevent loops in network switches and bridges by creating a loop-free logical topology.'),
	('ICMP','Internet Control Message Protocol','A protocol used for error reporting and operational queries in network communications.'),
	('BGP','Border Gateway Protocol','A protocol used to exchange routing information between different networks on the internet.'),
	('RARP','Reverse Address Resolution Protocol','A protocol used to map a known MAC address to an IP address.'),
	('LACP','Link Aggregation Control Protocol','A protocol used to combine multiple network connections into a single logical link for redundancy and increased bandwidth.'),
	('HSRP','Hot Standby Router Protocol','A redundancy protocol that allows multiple routers to work together to present the appearance of a single virtual router.'),
	('VRRP','Virtual Router Redundancy Protocol','A protocol that provides high availability by assigning a virtual IP address to a group of routers.'),
	('GLBP','Gateway Load Balancing Protocol','A protocol that provides load balancing and redundancy for gateway routers.'),
	('SDN','Software-Defined Networking','A networking architecture that allows network management to become directly programmable and agile.'),
	('NAT46','Network Address Translation 46','A technique used to facilitate communication between IPv4 and IPv6 networks.'),
	('IPsec','Internet Protocol Security','A suite of protocols used to secure Internet Protocol (IP) communications by authenticating and encrypting each IP packet.'),
	('GRE','Generic Routing Encapsulation','A protocol used to encapsulate a wide variety of network layer protocols into a point-to-point connection.'),
	('MPLS VPN','Multiprotocol Label Switching Virtual Private Network','A method for providing secure and efficient connectivity over a shared MPLS network.'),
	('DHCP Relay','DHCP Relay Agent','A component that forwards DHCP requests and replies between clients and servers across different subnets.'),
	('ARP Cache','Address Resolution Protocol Cache','A temporary storage of IP-to-MAC address mappings maintained by network devices to improve efficiency.'),
	('OSPF','Open Shortest Path First','A link-state routing protocol used to find the best path for packets as they pass through a set of connected networks.'),
	('EIGRP','Enhanced Interior Gateway Routing Protocol','A routing protocol that combines the advantages of link-state and distance-vector protocols.'),
	('IS-IS','Intermediate System to Intermediate System','A link-state routing protocol used to move information efficiently within a computer network.'),
	('DMVPN','Dynamic Multipoint Virtual Private Network','A Cisco technology that allows the creation of scalable VPNs using a combination of existing VPN technologies.'),
	('RSTP','Rapid Spanning Tree Protocol','An enhancement of the Spanning Tree Protocol (STP) that provides faster convergence.'),
	('BFD','Bidirectional Forwarding Detection','A protocol used to detect faults in the forwarding path between two routers.'),
	('VXLAN','Virtual Extensible LAN','A network virtualization technology that encapsulates Layer 2 Ethernet frames in Layer 3 UDP packets.'),
	('IPAM','IP Address Management','A method for planning, managing, and tracking IP address allocations in a network.'),
	('AAA','Authentication, Authorization, and Accounting','A framework for controlling access to network resources, enforcing policies, and auditing usage.'),
	('MPLS TE','MPLS Traffic Engineering','A technique used to optimize the flow of traffic across a network by controlling the paths data takes.'),
	('TFTP','Trivial File Transfer Protocol','A simple protocol used to transfer files, often used for bootstrapping or transferring configuration files.'),
	('SIP','Session Initiation Protocol','A protocol used to initiate, maintain, and terminate real-time communication sessions.');
